- Cargo.lock
- stream-to-file/Cargo.toml
- stream-to-file/src/main.rs
- stream-to-file/src/metrics.rs
Adds basic observability probe endpoints and Prometheus metrics.
Closes #10
> Add monitoring to stream-to-file

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/lib.rs
- common/src/metrics.rs
- schemas/dat1_digitizer_analog_trace_v1.fbs
- stream-to-file/src/main.rs
- trace-to-events/Cargo.toml
- trace-to-events/README.md
- trace-to-events/src/main.rs
- trace-to-events/src/metrics.rs
- trace-to-events/src/processing.rs
Provides very basic threshold based event generation from raw traces.
Also improve observability in existing apps (that have had the kagiyama treatment so far).
Closes #9
> Add trace-to-event app

- frame-assembler/src/main.rs
- live-plot/src/main.rs
- stream-to-file/src/main.rs
- trace-to-events/src/main.rs
Ensure all consumers commit at appropriate and consistent times.
> Fix consumer commit

- Cargo.lock
- Cargo.toml
- events-to-histogram/Cargo.toml
- events-to-histogram/README.md
- events-to-histogram/src/main.rs
- events-to-histogram/src/metrics.rs
- events-to-histogram/src/processing.rs
- schemas/hst1_histogram_v1.fbs
- streaming-types/build.rs
- streaming-types/src/lib.rs
- streaming-types/src/util.rs
> Implement basic online histogram generation

- simulator/src/main.rs
- stream-to-file/src/file/trace.rs
> Store sample rate in trace file

- Cargo.lock
- Cargo.toml
- common/src/lib.rs
- trace-archiver/Cargo.toml
- trace-archiver/Containerfile
- trace-archiver/README.md
- trace-archiver/src/file.rs
- trace-archiver/src/main.rs
- trace-archiver/src/metrics.rs
See the added README.md for a general description of this tool.
> Trace to HDF5 file archiver

- events-to-histogram/default.nix
- kafka-daq-report/default.nix
- simulator/default.nix
- stream-to-file/default.nix
- trace-archiver/default.nix
- trace-to-events/default.nix
> Prefix Container Image Names With 'supermusr-'

- Cargo.toml
- flake.nix
`nix develop` followed by `cargo build` now works.
> Fix and tidy devShell

- kafka-daq-report/src/app.rs
- kafka-daq-report/src/main.rs
> Kafka DAQ Report Metrics

- docs/Data Pipeline.md
Schematic of data flow through the pipeline
> Added Pipeline Sequence Diagram

- .adr-dir
- docs/adr/0001-record-architecture-decisions.md
- flake.nix
> Add ADR tooling and ADR adoption ADR

- docs/adr/0002-use-ess-like-architecture-for-streaming-components.md
- docs/adr/0003-initial-flatbuffer-formats.md
- docs/adr/0004-core-technologies-for-in-flight-data-processing-software.md
- docs/adr/0005-use-openmetrics.md
> Add some retrospective ADRs

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- common/src/tracer/tracer_engine.rs
- diagnostics/src/daq_trace/mod.rs
- diagnostics/src/main.rs
- diagnostics/src/message_debug.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
- run-simulator/src/main.rs
- simulator/src/main.rs
- trace-archiver-hdf5/src/main.rs
- trace-archiver-tdengine/src/main.rs
- trace-archiver/src/main.rs
- trace-reader/src/main.rs
- trace-telemetry-exporter/src/main.rs
- trace-to-events/src/main.rs
Haven't been able to revert changes in #216 so opening a new pull request instead.
Closes #199.
> Add CLI documentation.

- docs/adr/0007-standardise-error-handling.md
- docs/style.md
> Add ADR for error handling and update dev docs

- .github/workflows/ci.yml
- .github/workflows/component.yml
To test:
- Review changes to CI config
- See that formatting always runs (it should have ran on this PR)
> Reduce CI load

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/task.md
Adds GitHub issue templates.
This should help with issues containing enough information to be actionable.
Review the wording of the suggested templates.
> Add issue templates

- .github/workflows/component.yml
Fixes a typo that was missed in the original reduce CI load PR.
- review code
- ensure no other references to `matrix` remain in `component.yml`
> Fix typo in container image CI build stage

- docs/tracing.md
Added tracing.md to the docs folder.
1. Does tracing.md make sense, and is informative to a user familiar with the pipeline and with "some" knowledge of tracing/OpenTelemetry?
2. Does the diagram make sense? (Not for correctness yet, as the standard isn't yet implemented).
> Added tracing doc

- simulator/README.md
- simulator/src/integrated/build_messages.rs
- simulator/src/integrated/mod.rs
- simulator/src/integrated/send_messages.rs
- simulator/src/integrated/simulation.rs
- simulator/src/integrated/simulation_elements/digitiser_config.rs
- simulator/src/integrated/simulation_elements/event_list.rs
- simulator/src/integrated/simulation_elements/utils.rs
- simulator/src/integrated/simulation_engine/cache.rs
- simulator/src/integrated/simulation_engine/engine.rs
- simulator/src/main.rs
- simulator/src/runs/create_messages.rs
1. Updated Simulator spans to conform with OpenTelemetry policy.
2. Updated error handling to conform with new requirements.
3. Added `digitiser_` prefix to `trace` and `event` cli options to better describe their purpose.
Ensure spans and error handling conforms to policies.
> Updated Simulator Spans and Error Handling

- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/main.rs
Fixed error in `digitiser-aggregator` in which spans were not being properly nested. Moved the location of the call to `conditional_extract_to_current_span` method and reduced level of method `push` in `cache.rs`
Are changes as described?
> Moved location of call to conditional_extract_to_current_span

- trace-to-events/src/processing.rs
- trace-to-events/src/pulse_detection/detectors/advanced_muon_detector.rs
- trace-to-events/src/pulse_detection/detectors/mod.rs
- trace-to-events/src/pulse_detection/detectors/threshold_detector.rs
- trace-to-events/src/pulse_detection/iterators/event.rs
Changes behaviour of the fixed threshold discriminator in the event formation component to record the pulse height. The height is taken to be the maximum between the first crossing of the threshold and the first return.
General code quality. Has been tested and verified in pipeline simulation.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/266.
> Update fixed threshold discriminator to record pulse height

- nexus-writer/src/nexus/hdf5_file/run_file_components/event_run_file.rs
Changes the Nexus Writer to add a field recording the frame number.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/276.
> Added frame number field to nexus format

- nexus-writer/src/nexus/hdf5_file/run_file_components/event_run_file.rs
Added fields to record the `running` and `veto_flags` metadata to the nexus writer.
Has been tested on simulated data.
> Added fields

- .github/workflows/ci.yml
- Cargo.toml
- deny.toml
- flake.nix
- treefmt.toml
Adds cargo-deny, a dependency auditing tool.
- Code review
> Add cargo-deny

- Cargo.lock
- Cargo.toml
- deny.toml
- simulator/src/integrated/simulation.rs
- simulator/src/integrated/simulation_elements/event_list.rs
- simulator/src/integrated/simulation_elements/utils.rs
- simulator/src/integrated/simulation_engine/cache.rs
- trace-reader/src/main.rs
Updates some crates to their next major version.
Reduces enabled features where possible (should help dependency creep and compile times).
- code review
- test with simulated pipeline
> Update some crates and reduce enabled features

- docs/adr/0009-nexus-file-format.md
Added ADR for the Nexus file format.
Check the ADR is okay.
Closes [ADR for NeXus file format](https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/240).
> Added NeXus ADR

- flake.nix
- trace-telemetry-exporter/src/main.rs
- trace-to-events/src/processing.rs
- trace-to-events/src/pulse_detection/iterators/save_to_file.rs
- trace-viewer-tui/src/graphics/svg.rs
Updates to rust 1.88.
Adapts to a few linting changes.
Review changes.
Ensure pipeline builds as before.
> Update to rust 1.88
