- Cargo.lock
- simulator/Cargo.toml
- simulator/src/main.rs
Allows simulator to output in either single shot or continuous mode. CLI documentation should be sufficient to describe what these modes do.
> simulator: add single shot mode

- Cargo.lock
- common/src/lib.rs
- stream-to-file/Cargo.toml
- stream-to-file/src/file/base.rs
- stream-to-file/src/file/event.rs
- stream-to-file/src/file/trace.rs
- stream-to-file/src/main.rs
Correctly handle multiple digitizers when saving trace files.
To test:
- Start trace saver for 3 digitizers, ensure the consumer group is up to date
- Run the simulator for each digitiser in turn, ideally for an obviously different length of time
- Stop trace saver and load the file in https://h5web.panosc.eu/h5wasm
- See that `frame_start_index`:
- increments in the measurement count given to the simulator
- has no value is repeated
- has the correct amount of entries
- See that `detector_data`:
- has the expected dimensions for the number of channels
- has data from all detectors
- has simulator frame and digitizer ID markers in the correct positions
Closes #17
> Multiple digitizers trace saving

- events-to-histogram/src/processing.rs
- live-plot/src/backend.rs
- stream-to-file/src/file/base.rs
- stream-to-file/src/file/event.rs
- stream-to-file/src/file/trace/tests/mod.rs
- streaming-types/src/lib.rs
Originally noticed here: https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/actions/runs/4128980262/jobs/7134079097
> Ignore more warnings from flatbuffer generated code

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- events-to-histogram/src/main.rs
- simulator/src/main.rs
- stream-to-file/src/main.rs
- trace-archiver/src/main.rs
- trace-to-events/src/main.rs
Allows the `username` and `password` command line arguments to be omitted, in which case an unauthenticated Kafka connection is able to be created instead.
> Unauthenticated Kafka Connections

- streaming-types/src/lib.rs
Ignores `clippy::unnecessary_cast` in `flatc` generated code.
> Add clippy::unnecessary_cast to flatbuffer ignore rules

- Cargo.toml
- common/Cargo.toml
- events-to-histogram/Cargo.toml
- kafka-daq-report/Cargo.toml
- simulator/Cargo.toml
- stream-to-file/Cargo.toml
- streaming-types/Cargo.toml
- trace-archiver/Cargo.toml
- trace-to-events/Cargo.toml
Move duplicate code to the workspace `Cargo.toml` file and inherit dependencies.
> Inherit metadata and dependencies from Cargo workspace

- rust-toolchain.toml
> Remove Rust toolchain file

- .github/workflows/ci.yml
This will catch things like Cargo.lock being out of date with changes to Cargo.toml, etc.
> Add a CI step to check that there are no changed files after Clippy

- run-simulator/Cargo.toml
- run-simulator/src/main.rs
Adds OpenTelemetry and some tracing to the run simulator component.
- otel_endpoint optional command line parameter added
- init_tracer function sets up OpenTelemetry if otel_endpoint is specified and runs tracing_subscriber::fmt::init() otherwise
- Propagates current trace to the next component via the Kafka header.
> Add open telemetry to run simulator

- nexus-writer/Cargo.toml
- nexus-writer/src/main.rs
- nexus-writer/src/nexus/builder.rs
- nexus-writer/src/nexus/mod.rs
- nexus-writer/src/nexus/run.rs
- nexus-writer/src/spanned_run.rs
Adds OpenTelemetry and some tracing to the nexus writer component.
- otel_endpoint optional command line parameter added
- init_tracer function sets up OpenTelemetry if otel_endpoint is specified and runs tracing_subscriber::fmt::init() otherwise
- Extracts external trace from consumed Kafka headers if present and sets current trace as a child of it.
- Associates a trace with each Run object, to which all relevant external traces are collected.
> Add open telemetry to nexus writer

- digitiser-aggregator/src/frame/aggregated.rs
- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/mod.rs
- digitiser-aggregator/src/frame/partial.rs
- digitiser-aggregator/src/main.rs
- digitiser-aggregator/src/spanned_frame.rs
Adds OpenTelemetry and some tracing to the aggregator component.
- otel_endpoint optional command line parameter added
- init_tracer function sets up OpenTelemetry if otel_endpoint is specified and runs tracing_subscriber::fmt::init() otherwise
- Extracts external trace from consumed Kafka headers if present and sets current trace as a child of it.
- Associates a trace with each Frame object, to which all relevant external traces are collected. (I'm not 100% happy with how fiddly this is - modifications are needed to the PartialFrame and AggregatedFrame functionality - it suggests there could be room to streamline the Spanned generic type in the future, but it works fine for the moment).
> Add open telemetry to digitiser aggregator

- simulator/src/main.rs
- simulator/src/message.rs
Adds OpenTelemetry and some tracing to the trace simulator component.
- otel_endpoint optional command line parameter added
- init_tracer function sets up OpenTelemetry if otel_endpoint is specified and runs tracing_subscriber::fmt::init() otherwise
- Propagates current trace to the next component via the Kafka header.
> Add open telemetry to simulator

- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/partial.rs
- streaming-types/src/frame_metadata.rs
Digitiser-Aggregator was assigning digitiser messages to different frames because these messages had different veto flags. These modifications fixes that issue, and aggregates the veto flags by bitwise OR.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/184.
> Fix veto flag aggregation issue

- digitiser-aggregator/src/main.rs
- trace-to-events/src/main.rs
Message producing in digitiser-aggregator and trace-to-events now uses multithreading, freeing the main thread to continue consuming messages.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/183
> Implement join set multithreading for aggregator and event formation

- digitiser-aggregator/src/main.rs
Changed aggregator reaction to messages with bad metadata (namely invalid timestamps) from panic, to discard message, issue warning, and continue.
> Fixed Digitiser-aggregator Panic on bad Metadata

- trace-to-events/README.md
- trace-to-events/src/parameters.rs
- trace-to-events/src/processing.rs
- trace-to-events/src/pulse_detection/detectors/advanced_muon_detector.rs
In trace-to-events: changes name of constant phase discriminator mode to fixed threshold discriminator
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/141
> Name change of mode in trace to events

- docs/adr/0007-standardise-error-handling.md
- docs/style.md
Further restrict the use of `anyhow`.
The flexibility of this has led to some quite sloppy error handling, particularly cases where errors that can be recovered from (e.g. only affecting a single frame of data) are propagated to the point of being terminal (at which point they may as well have just panicked and provided a little more information about the error).
Explicitly list the things that should not be done and are best not to do in the developer docs.
Note the desire to address other panicking operations and functions later on.
- review revised wording of ADR and developer style guide
- see that the proposed guidelines are reasonable, clear/unambiguous and generally make sense
> Update ADR and docs for Rust error handling

- common/src/spanned.rs
- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/partial.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
- nexus-writer/src/nexus/run.rs
Introduced SpannedAggregator trait to encapsulate the span-aggregating behaviour of digitiser_aggregator::Frame and nexus_writer::Run.
Ensure changes are as described.
> Added SpannedAggregator to common crate

- common/src/lib.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/event_run_file.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/timeseries_file.rs
- nexus-writer/src/nexus/mod.rs
~~Moved the constant TIMESTAMP_FORMAT to common crate from the Nexus-Writer crate. This constant is used to parse `DateTime` objects into strings. Hence it is more logical to have a common format in a logical place.~~
Removed the constant `TIMESTAMP_FORMAT` from nexus-writer, and replaced its usage with `to_rfc3339()`.
Ensure changes to code are as described above.
> Removed TIMESTAMP_FORMAT

- common/src/tracer/mod.rs
- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
Added `record_metadata_fields_to_span` macro to populate spans which are setup to record metadata fields.
Does code reflect description above, and does the attached doc comment make sense and adequately explain its purpose.
> Added record_metadata_fields_to_span macro to common crate

- Cargo.lock
- simulator/Cargo.toml
- simulator/src/integrated/build_messages.rs
- simulator/src/integrated/mod.rs
- simulator/src/integrated/send_messages.rs
- simulator/src/integrated/simulation.rs
- simulator/src/integrated/simulation_elements/digitiser_config.rs
- simulator/src/integrated/simulation_elements/event_list.rs
- simulator/src/integrated/simulation_elements/noise.rs
- simulator/src/integrated/simulation_elements/pulses.rs
- simulator/src/integrated/simulation_elements/run_messages.rs
- simulator/src/integrated/simulation_elements/utils.rs
- simulator/src/integrated/simulation_engine/actions.rs
- simulator/src/integrated/simulation_engine/engine.rs
- simulator/src/main.rs
- simulator/src/runs/create_messages.rs
- simulator/src/runs/mod.rs
- simulator/src/runs/runlog.rs
- simulator/src/runs/sample_environment.rs
1. Changed `unwrap`s to `expect`s in `build_messages.rs`
2. Changed `send_trace_message` to `send_digitiser_trace_message` and integrated edits in `send_messages.rs`,  `simulation.rs`, `engine.rs` and others.
3. Added `Trace` struct for channel traces in `event_lists.rs` and refactored
4. Added `IntConstant` and `TextConstant` types
5. Added `EnsureDelayMs` action
6. Improved error handling
General code review as the simulator was successfully tested in the pipeline.
> Improve simulator functionality

- trace-to-events/src/main.rs
- trace-to-events/src/processing.rs
1. Refactored main loop into functions `process_kafka_message` and `process_digitiser_trace_message`
2. Added metadata and digitiser id fields to instrumented spans of the above functions and functions in `processing.rs`.
Are changes as described above?
> Refactored functions in main.rs and added fields to spans

- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/partial.rs
- digitiser-aggregator/src/main.rs
- streaming-types/src/frame_metadata.rs
1. ~~Swapped `VecDeque` to `HashMap<FrameMetadata,_>` and implemented resulting changes~~
2. Added metadata to `push` function instrumentation.
3. Added `get_num_partial_frames` function.
4. Added `test_metadata_equality` test.
5. ~~`push` now returns `&impl SpannedAggregator`, and dependence on `FindSpan(Mut)` removed.~~
1. Added metadata to `Frame` span.
1. Refactored `on_message` to `process_kafka_message` and `process_digitiser_event_list_message` functions.
2. Added metadata and other fields to `process_kafka_message` and `process_digitiser_event_list_message` instrumentation
3. Instrumented `root_as_digitizer_event_list_message` by wrapping with `span_of_root_as_digitizer_event_list_message`
1. ~~Implemented `Hash` trait for `FrameMetadata`~~
2. Implemented `PartialEq` for …
> Updates to digitiser aggregator, and adding fields to spans

- docs/cycle_20243_testing_on_hifi.md
- docs/cycle_20243_testing_on_musr.md
Adds test plans for the 2024/3 cycle, listing the items to be tested and brief overview of what should be verified.
Closes #140 
- Review test plans, see that they generally make sense
> Cycle 2024/3 test plans

- diagnostics/README.md
- diagnostics/src/daq_trace/app.rs
- diagnostics/src/daq_trace/data.rs
- diagnostics/src/daq_trace/mod.rs
- diagnostics/src/daq_trace/ui.rs
1. General refactoring to make code more idiomatic
2. Moved the constructor and display functionality of `DigitiserData` to its own file.
3. Reworked the column structure to group up related items (as described in the README).
4. Added `weights` options to the column widths, making some columns larger than others.
5. Introduced `Channel` column which monitors a single channel (adjustable with left/right keys) and displays channel id and sample range.
Test with command such as
```bash
cargo run --bin diagnostics daq-trace --broker 130.246.55.29:9092 --topic daq-traces-in --group vis-3
```
when a run is in progress from the chosen broker.
> Diagnostic refactoring

- nexus-writer/src/main.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/run.rs
Added a feature to nexus-writer to allow the nexus file to be moved from a temporary location to another, when the run is determined to be completed by nexus-writer.
The move is performed async to prevent other runs from being blocked.
General code quality review (full testing requires pipeline simulation).
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/262.
> Add nexus writer move completed file feature

- nexus-writer/src/nexus/hdf5_file/run_file.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/event_run_file.rs
Applies to Nexus Writer.
In the cases where frames arrive out of order, it is possible for `event_time_zero` to be 'negative'. As `event_time_zero` is unsigned this results in integer wrap around, giving misleading results. This follows from the `offset` attribute (which is used to calculate `event_time_zero`) being set to the time of the first frame message.
This PR instead sets `offset` to the time of the run start. As any frames before this time are not considered part of the run, this change should make `event_time_zero` robust to wrap around errors.
The change has been tested and verified on simulated data.
> Nexus Writer: Make Frame Times Relative to Run Start instead of First Received Frame

- Cargo.toml
- digitiser-aggregator/src/main.rs
- Replaces `JoinSet` method of producing `frame_event_list` messages to Kakfa, with a dedicated long-running thread which is tasked with emitting frames to Kafka.
- Every call to `cache_poll` drains the cache of completed frames from the front, until an incomplete frame is reached, and sends them to the dedicated thread.
- Frames are emitted in the order they were begun (i.e. when its first digitiser event message arrived).
General code review. This change been tested and verified with simulated data, and on HiFi.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/265.
> Fix excessive memory usage in aggregator

- nexus-writer/src/main.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/hdf5_file/run_file.rs
- nexus-writer/src/nexus/mod.rs
- nexus-writer/src/nexus/run.rs
Adds an optional cli option in nexus-writer "configuration-options" which allows a string of text to be written in the resulting Nexus File in the attribute "raw_data_1/detector_1/program_name/configuration".
Here, parameters such as the event detection threshold should be stored.
> Added configuration option

- nexus-writer/src/nexus/engine.rs
Bug fix.
In very particular circumstances a vector is accessed out of bounds.
When two runs are present in the run cache, and complete at the same time the `flush` method will likely try to access the `run_cache` deque out of bounds.
This bug was missed due to non-idiomatic code being used. It has been replaced and a suitable test added to check this (albeit unlikely) use case.
Tested on simulated data.
> Fixes flushed runs index bug

- nexus-writer/src/main.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/hdf5_file/run_file.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/runlog_file.rs
- nexus-writer/src/nexus/run.rs
- nexus-writer/src/nexus/run_parameters.rs
Adds "emergency_stop" function, so that when a RunStart is encountered whilst a run is currently running, the current run is halted and a new run begins.
If the new RunStart message has the same run_name field as the previous, this results in the previous run being overwritten.
Behaviour has been tested with simulated runs.
> Missing run stop prompts new run

- common/src/tracer/otel_tracer.rs
- common/src/tracer/tracer_engine.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
- simulator/src/main.rs
- trace-to-events/src/main.rs
Adds extra command line option, which prepends the "service.name" field for OpenTelemetry with an optional string. Useful for distinguishing telemetry from different instances of the pipeline running in parallel.
Tested on simulated data.
> Otel Tag Option

- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/partial.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
- In `cache_poll`, the `Frame Completed` span now occurs for every frame dispatched from the cache. Allowing us to see how many are unqueued at the same time.
- Fixes a bug whereby complete frames in the queue are marked as expired because they were behind incomplete frames.
- Removed `debug!("{args}");` log statement.
Tested on simulated data.
> Changes structure of `Frame Completed` span in nexus writer

- trace-to-events/src/main.rs
Producer threads created in the `trace-to-events` create were not being joined with the main thread, possibly causing excessive memory usage.
This PR introduces a `tokio::select` statement which joins completed threads without waiting for them.
Tested on simulated and hifi input.
> Need to Join Completed Producer Threads in Trace to Events

- trace-to-events/src/main.rs
The current event-formation component creates a new thread to produce each outgoing message resulting in the overhead associated with thread for each message. In this PR, the component creates a single persistent thread for producing messages to Kafka, and transfers processed traces from the main thread to this thread via a channel.
Commentary on the new architecture is welcome. Is this a good change?
Has been tested on simulated and Kafka data.
> Single producer thread event formation

- digitiser-aggregator/src/main.rs
Enabled digitisers to be specified as a comma separated list in cli instead of as repeated arguments.
This is useful in docker compose.
> Add comma separated digitiser argument in aggregator

- digitiser-aggregator/src/data/event.rs
- digitiser-aggregator/src/frame/aggregated.rs
- schemas/aev2_frame_assembled_event_v2.fbs
- simulator/src/integrated/build_messages.rs
Adds two extra fields to the assembled frame flatbuffer messages, one to indicate if the frame is considered complete and another to list the digitisers that contributed data to this frame.
This data is already collected in the building of the partial frame, this just adds propagation of it to the assembled message.
- Test using simulated data
- Pipeline should work as it always did
> Digitizer reporting in assembled messages

- digitiser-aggregator/src/main.rs
Changed behaviour of aggregator to block when the message send queue is full rather than terminate. The previous behaviour prevented the aggregator from restarting after a brief time offline, due to the backlog building up form the trace-to-events component.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/293.
Tested with HiFi data.
> Fixed Aggregator Bug

- nexus-writer/src/main.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/hdf5_file/run_file.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/event_run_file.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/runlog_file.rs
- nexus-writer/src/nexus/run.rs
Writes the `complete` flag of each frame into the nexus file, as well as recording the digitisers present as a run log, in the case of `complete == false`.
Also modified the type of the time field in the runlogs: `i32` changed to `u64` as `i32` does not have the range for recording `ns` precision.
Please excuse the use of `anyhow`, will be changed later.
> Propagate incomplete frame data

- simulator/src/integrated/simulation.rs
- simulator/src/integrated/simulation_engine/actions.rs
- simulator/src/integrated/simulation_engine/engine.rs
Added action to the simulator to allow the frame timestamp to be rewound as well as advanced. This allows for more testing options.
> Allow simulator action to rewind the timestamp

- digitiser-aggregator/Cargo.toml
- digitiser-aggregator/src/frame/cache.rs
In the aggregator: prevents new frames from being created whose timestamp is earlier than or equal to any that have previously been dispatched. That is, if a digitiser messages arrives late, then if it's frame is still in the cache, it is aggregated into that frame, otherwise it is discarded and a warning emitted.
Closes https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/288.
Note that we still assume that each frame's initial digitiser message appears in chronological order.
Has been tested on simulated data.
> Prevent out of order frames

- Cargo.toml
- common/src/tracer/otel_tracer.rs
- common/src/tracer/propagator.rs
- common/src/tracer/tracer_engine.rs
- flake.nix
- simulator/src/integrated/simulation_engine/actions.rs
- trace-archiver-tdengine/src/tdengine/error.rs
- trace-archiver-tdengine/src/tdengine/wrapper.rs
- trace-reader/src/loader.rs
- trace-reader/src/processing.rs
- trace-to-events/src/pulse_detection/datatype/eventpoint.rs
- trace-to-events/src/pulse_detection/datatype/tracepoint.rs
- trace-to-events/src/pulse_detection/datatype/tracevalue.rs
- trace-to-events/src/pulse_detection/detectors/mod.rs
- trace-to-events/src/pulse_detection/detectors/threshold_detector.rs
- trace-to-events/src/pulse_detection/window/mod.rs
Moves to Rust 1.84.
Something higher than 1.80 was required to move to the maintained fork of `hdf5`.
This also addresses a few new warnings generated.
- basic test with simulated data
- review modified code
> Upgrade Rust version to 1.84

- Cargo.lock
- Cargo.toml
- trace-archiver-tdengine/Cargo.toml
- trace-archiver-tdengine/src/tdengine/mod.rs
- trace-archiver-tdengine/src/tdengine/wrapper.rs
`async_trait` is no longer required for our direct use cases.
- Code review
> Remove use of async_trait

- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/main.rs
Minor code change to allow OpenTelemetry to record when a digitiser message is discarded by the aggregator for being irreparably out of chronological order.
General code check.
Has been tested with simulated and HiFi data.
> Add discarded flag to digitiser aggregator spans

- Cargo.lock
- Cargo.toml
- flake.lock
- flake.nix
Updates nixpkgs version to 24.11.
- see that pipeline still works in basic simulated context
> Update nixpkgs to 24.11

- .github/workflows/ci.yml
- .github/workflows/component.yml
See https://determinate.systems/posts/magic-nix-cache-free-tier-eol/.
Removes Nix Magic Cache before it will stop working.
- code review
> Remove Magic Nix Cache

- common/src/tracer/mod.rs
- common/src/tracer/otel_tracer.rs
- common/src/tracer/tracer_engine.rs
- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/partial.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/run.rs
- simulator/src/integrated/build_messages.rs
- simulator/src/integrated/mod.rs
- simulator/src/integrated/send_messages.rs
- simulator/src/integrated/simulation.rs
- simulator/src/integrated/simulation_elements/digitiser_config.rs
- simulator/src/integrated/simulation_elements/event_list.rs
- simulator/src/integrated/simulation_engine/engine.rs
- simulator/src/main.rs
- trace-to-events/src/channels.rs
- trace-to-events/src/main.rs
- trace-to-events/src/processing.rs
Changes the way we set OpenTelemetry levels and tidies up some spans.
- Removed `otel_level` cli option from all components.
- Modified OpenTelemetry filter layer to use environment variable "OTEL_LOG" to determine which level to filter crates/modules on.
- Removed references to the `otel` target and `target = "otel"` syntax in spans/events (This accounts for most files changed). This target is not really useful, though OpenTelemetry-only targets may be introduced in the future.
- In `trace-to-events`, functions processing individual channels moved to their own file `channels.rs`. This allows the observability level for these to be set via including `trace_to_events::channels=????` in `OTEL_LOG`. At present use `info` to include channels, and `warn/error/off` to exclude.
- Level of …
> Set open telemetry levels via an environment variable

- trace-to-events/src/main.rs
- trace-to-events/src/processing.rs
Allows querying an average event rate via Prometheus (InfluxDB probably has a similar feature).
- Run simulated pipeline
- `curl` the metrics endpoint of `trace-to-events`
- See that the event count increases as expected for each digitiser and channel
Closes #305
> trace-to-events: record the cumulative number of events per channel

- nexus-writer/src/main.rs
- nexus-writer/src/message_handlers.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/hdf5_file/run_file.rs
- nexus-writer/src/nexus/hdf5_file/run_file_components/selog_file.rs
- nexus-writer/src/nexus/run.rs
Sample environment logs can be delivered using both `f144_logdata` and `se00_data` schemas. The current nexus writer identifies SELogs by its schema, regardless of which topic it's delivered on. This causes SELogs to be written as RunLogs.
This PR causes the writer to identify each type of Kafka message by the topic it's delivered on, validate it's schema, and process it appropriately.
- Topics are stored in a new struct `Topics` which is passed by reference to functions.
- The `process_payload` function is refactored into functions which handle each topic separately.
- The functions  referred to in `process_payload` are moved into a separate file.
- A `SampleEnvironmentLog` enum is introduced to handle the different schemas that can be used.
General code review
Tested with HiFi
(concise …
> Route se logs and run logs correctly

- nexus-writer/src/flush_to_archive.rs
- nexus-writer/src/main.rs
- nexus-writer/src/nexus/engine.rs
- nexus-writer/src/nexus/error.rs
- nexus-writer/src/nexus/mod.rs
- nexus-writer/src/nexus/run.rs
- nexus-writer/src/nexus/run_parameters.rs
- nexus-writer/src/nexus/settings.rs
- Renames CLI options `file_name` and `archive_name` to `local_path` and `archive_path` respectively.
- Run files are stored in ~`local_path/temp`~ `local_path/` whilst being built up, and moved to `local_path/completed/` when finished. Failure of this file move results in component termination, and logging.
- Introduces CLI option `archive_flush_interval_sec` which tunes how often nexus-writer moves all files in `local_path/completed` to `archive_path`. `archive_flush_interval_sec` defaults to 60 (seconds) if not specified. Failure of these operations **does not** result in component termination, but warnings are emitted.
- Removed archive code from the `run.rs` and `engine.rs` to `flush_to_archive.rs` file.
- Code related to creating directory structure moved from `engine.rs` to …
> Fine grained separation of files in nexus writer

- digitiser-aggregator/src/frame/cache.rs
- digitiser-aggregator/src/frame/mod.rs
- digitiser-aggregator/src/frame/partial.rs
- digitiser-aggregator/src/main.rs
- The `digitiser-aggregator` checks whether the list of digitiser ids, and reject a digitiser message if its id is already present, and emits a warning.
- Replaces the tracing span field "is_discarded" with the pair "timestamp_too_early" and "id_already_present".
- Defines `RejectMessageError` struct which reports the reason for the digitiser message being rejected.
Closes [When a frame receives multiple messages from the same digitiser](https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/issues/297).
Has been tested on simulated data.
> When frame receives repeated digitiser messages

- nexus-writer/src/nexus_structure/entry/mod.rs
Typo in the name of the `periods` group in the nexus file, changed from `period` to `periods`
Was tested on simulated code.
> Renamed period to periods

- common/src/lib.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/error.rs
- nexus-writer/src/kafka_topic_interface.rs
- nexus-writer/src/main.rs
- nexus-writer/src/message_handlers.rs
- nexus-writer/src/run_engine/engine.rs
- nexus-writer/src/run_engine/mod.rs
- nexus-writer/src/run_engine/run/mod.rs
- nexus-writer/src/run_engine/run/run_parameters.rs
- trace-archiver-hdf5/src/main.rs
- trace-archiver-tdengine/src/main.rs
- trace-telemetry-exporter/src/main.rs
- trace-to-events/src/main.rs
- Modifies `create_default_consumer` in common crate to make `topics_to_subscribe` parameter optional. Also pushes error handling responsability to the caller.
- Updates all non nexus-writer components appropriately.
- Encapsulates all `NexusEngine` dependencies into a trait to aid future extension.
- Injects new dependency `KafkaTopicSubscriber` to `NexusEngine` which allows `NexusEngine` to switch between two topic subscriber modes: "Full" (which subscribes to all topics) and "Continuous" (which subscribes to all but SampleEnvironmentLogs and Alarms).
Pending further info from Peter, the RunLog topic could also be removed from the "Continuous" mode if required, at the moment it is not removed.
Closes [Record sample env logs since end of last run in current …
> Pause sample env topic between runs

- Cargo.lock
- Cargo.toml
- common/src/lib.rs
- diagnostics/default.nix
- digitiser-aggregator/default.nix
- flake.nix
- nexus-writer/default.nix
- simulator/default.nix
- trace-reader/default.nix
- trace-telemetry-exporter/default.nix
- trace-to-events/default.nix
Provide the zstd library and enable zstd compression by default in all components that interact with Kafka.
This is partly experimental to see what the effects are on compute requirements and network throughput are for data "inside" the pipeline.
- Run a demo pipeline, using the container images, with and without these changes and see that the same output is still obtained.
- Verify that the data produced is actually compressed (can be done via Redpanda Console).
> Enable zstd compression

- .github/workflows/ci.yml
Some more thought is needed how container images are built for this.
See that trace-viewer does not appear in CI jobs.
> Temporarily remove trace-viewer from CI

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/metrics.rs
- digitiser-aggregator/src/main.rs
- nexus-writer/src/main.rs
- nexus-writer/src/message_handlers.rs
- trace-to-events/Cargo.toml
- trace-to-events/src/main.rs
Adds "muon_data_pipeline_" prefix to all common metric names.
Aids in finding metrics in the collection of other things collected by Prometheus.
- Run any component that exposes metrics
- `curl` the metrics endpoint
- See that metrics names have the expected prefix
(or code review is realistically enough)
> Prefix metric names with `muon_data_pipeline_`

- trace-viewer/src/finder/task/binary_by_timestamp.rs
- trace-viewer/src/finder/topic_searcher/searcher.rs
- trace-viewer/src/sessions/session.rs
- trace-viewer/src/structs/digitiser_messages.rs
- trace-viewer/src/structs/server_only/search_results.rs
Fixes bug in which some channels and traces are not viewable when selected. This is due to inconsistent ordering of results.
This change replaces the `HashMap` with a `BTreeMap` which preserves order of the keys.
- General Code review.
- Ensure the website shows results in order of time/digitiser id, and test traces can be displayed from a wide range of the results (no need to test them all).
```shell
RUST_LOG=debug cargo leptos --log wasm watch -- --broker="172.16.113.245:9092" --consumer-group viewer --trace-topic Traces --digitiser-event-topic Events --name Test --channels 14 --channels 50 --digitiser-ids 3 --timestamp 2025-08-12T11:28:19.1Z --number 20 --link-to-redpanda-console="http://130.246.55.29:8080/overview" --broker-name="Dan K Test Broker"
```
> Trace viewer fix ordering bug

- trace-viewer/src/finder/task/binary_by_timestamp.rs
- trace-viewer/src/finder/topic_searcher/iterators/back_step.rs
- trace-viewer/src/finder/topic_searcher/iterators/binary.rs
- trace-viewer/src/finder/topic_searcher/iterators/forward.rs
- trace-viewer/src/finder/topic_searcher/iterators/mod.rs
- trace-viewer/src/finder/topic_searcher/searcher.rs
- trace-viewer/src/main.rs
- trace-viewer/src/structs/server_only/search_results.rs
- Adds some tracing to the trace-viewer, useful for diagnostics
- Adds a tool to detect out of chronological order messages in the `ForwardSearchIter` iterator.
General code review
> Extra tracing, and non-chronological message detector in trace viewer

- trace-viewer/src/app/sections/results/search_results/mod.rs
- trace-viewer/src/app/sections/search/context.rs
- trace-viewer/src/app/sections/search/search_section.rs
- trace-viewer/src/app/sections/search/search_settings.rs
- trace-viewer/src/finder/search_engine.rs
- trace-viewer/src/finder/task/binary_by_timestamp.rs
- trace-viewer/src/finder/task/dragnet.rs
- trace-viewer/src/finder/task/mod.rs
- trace-viewer/src/finder/topic_searcher/iterators/dragnet.rs
- trace-viewer/src/finder/topic_searcher/iterators/mod.rs
- trace-viewer/src/finder/topic_searcher/searcher.rs
- trace-viewer/src/structs/search.rs
Adds a new search option (dragnet searching, name is a placeholder), which uses binary search to locate a given timestamp, jumps back the specified number of messages then searches forwards for the specified number of messages.
This is intended as a blunt instrument mode, which does not rely on messages being in chronological order. This allows the tool to be used to help diagnose issues with messages appearing out of order in the broker.
The layout on the webpage is confusing, but this will be updated in a future PR.
Please review after https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline/pull/409 is merged.
> Add extra search option in trace viewer
